apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudclass-cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cloudclass-networking
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v0.15.2
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  project: cloudclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
