apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cloudclass-networking
spec:
  destination:
    name: ""
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.0.0-beta.1
    chart: cert-manager
  project: cloudclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
