apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "cloudclass-networking-cert-manager"
spec:
  destination:
    name: ""
    namespace: cloudclass-networking
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://kubernetes-charts.storage.googleapis.com/"
    targetRevision: v0.6.7
    chart: cert-manager
  project: cloudclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cloudclass-networking
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jochem@cloudclass.be
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cloudclass-networking
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jochem@cloudclass.be
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
