apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudclass-ingress
  namespace: cloudclass-networking
spec:
  destination:
    name: ""
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://kubernetes.github.io/ingress-nginx/"
    targetRevision: 2.13.0
    chart: ingress-nginx
  project: cloudclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
