apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "cloudclass-core-sealed-secrets"
spec:
  destination:
    name: "cloudclass-core-sealed-secrets"
    namespace: cloudclass-core
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://kubernetes-charts.storage.googleapis.com/"
    targetRevision: 1.10.4
    chart: sealed-secrets
  project: "cloudclass"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
