apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloudclass-services-evaluation-ingress
spec:
  rules:
  - host: evaluation.jochem.codes
    http:
      paths:
      - backend:
          serviceName: cloudclass-services-evaluation-application
          servicePort: 80